# Generated by Django 3.0 on 2019-12-13 13:50

import autoslug.fields
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191213_1239'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=60)),
                ('mobile', models.IntegerField()),
                ('email', models.EmailField(max_length=40)),
                ('website', models.URLField(max_length=160)),
            ],
        ),
        migrations.CreateModel(
            name='tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title')),
                ('content', models.TextField()),
                ('utimestamp', models.DateTimeField(default=datetime.datetime(2019, 12, 13, 13, 50, 2, 755756, tzinfo=utc))),
            ],
        ),
        migrations.AlterField(
            model_name='categories',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='title',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='categories',
            name='utimestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 13, 13, 50, 2, 754098, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 13, 13, 50, 2, 753037, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=60),
        ),
    ]
