# Generated by Django 3.0 on 2019-12-13 13:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20191213_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='utimestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 13, 13, 52, 27, 887761, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 13, 13, 52, 27, 886748, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tags',
            name='utimestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 13, 13, 52, 27, 889384, tzinfo=utc)),
        ),
    ]
