# Generated by Django 3.0 on 2019-12-13 14:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20191213_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title')),
                ('content', models.TextField()),
                ('utimestamp', models.DateTimeField(default=datetime.datetime(2019, 12, 13, 14, 17, 49, 904973, tzinfo=utc))),
            ],
        ),
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
        migrations.DeleteModel(
            name='tags',
        ),
        migrations.AlterField(
            model_name='categories',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='utimestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 13, 14, 17, 49, 903310, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 13, 14, 17, 49, 902241, tzinfo=utc)),
        ),
    ]
