# Generated by Django 3.0 on 2019-12-13 14:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20191213_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='utimestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 13, 14, 34, 16, 890892, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 13, 14, 34, 16, 889727, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tag',
            name='utimestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 13, 14, 34, 16, 892519, tzinfo=utc)),
        ),
    ]
